# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: my-users-serverless-mongodb-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  timeout: 12



functions:
  # Create User
  createUser:
    handler: src/users.createUser
    events:
      - http:
          method: POST
          path: create-user

  # Update User
  updateUser:
    handler: src/users.updateUser
    events:
      - http:
          method: PUT
          path: update-user/{id}

  # Delete User
  deleteUser:
    handler: src/users.deleteUser
    events:
      - http:
          method: DELETE
          path: delete-user/{id}

  # Read One user
  getUser:
    handler: src/users.getUser
    events:
      - http:
          method: GET
          path: users/{id}

  # Read all users
  getUsers:
    handler: src/users.getUsers
    events:
      - http:
          method: GET
          path: users

  getSwaggerYml:
    handler: src/swagger.getYml
    events:
      - http:
          method: GET
          path: swagger.yml

  getSwaggerUi:
    handler: src/swagger.getUi
    events:
      - http:
          method: GET
          path: swagger
plugins:
  - serverless-offline
